// RBAC constants: stable permission & role identifiers plus role->permission mapping.
// Extend by adding new PERMISSIONS keys and including them in relevant ROLES_PERMISSIONS entries.
export const PERMISSIONS = {
  // Core / Dashboard
  VIEW_DASHBOARD: "VIEW:DASHBOARD",

  // Users (existing internal management)
  READ_USERS: "READ:USERS",
  CREATE_USERS: "CREATE:USERS",
  EDIT_USERS: "EDIT:USERS",
  DELETE_USERS: "DELETE:USERS",
  VIEW_USERS: "VIEW:USERS",

    VIEW_PURCHASE_ORDERS: "VIEW:PURCHASE_ORDERS",

      VIEW_PAYSLIPS: "VIEW:PAYSLIPS",

  // States
  READ_STATES: "READ:STATES",
  CREATE_STATES: "CREATE:STATES",
  EDIT_STATES: "EDIT:STATES",
  DELETE_STATES: "DELETE:STATES",
  VIEW_STATES: "VIEW:STATES",

  // StockAdjustments
  READ_STOCK_ADJUSTMENTS: "READ:STOCK_ADJUSTMENTS",
  CREATE_STOCK_ADJUSTMENTS: "CREATE:STOCK_ADJUSTMENTS",
  VIEW_STOCK_ADJUSTMENTS: "VIEW:STOCK_ADJUSTMENTS",

  // Stocks
  READ_STOCKS: "READ:STOCKS",
  VIEW_STOCKS: "VIEW:STOCKS",

  // Cities
  READ_CITIES: "READ:CITIES",
  CREATE_CITIES: "CREATE:CITIES",
  EDIT_CITIES: "EDIT:CITIES",
  DELETE_CITIES: "DELETE:CITIES",
  VIEW_CITIES: "VIEW:CITIES",

  // Companies
  READ_COMPANIES: "READ:COMPANIES",
  CREATE_COMPANIES: "CREATE:COMPANIES",
  EDIT_COMPANIES: "EDIT:COMPANIES",
  DELETE_COMPANIES: "DELETE:COMPANIES",
  VIEW_COMPANIES: "VIEW:COMPANIES",

  // Sites
  READ_SITES: "READ:SITES", //get
  CREATE_SITES: "CREATE:SITES", //post
  EDIT_SITES: "EDIT:SITES", //put
  DELETE_SITES: "DELETE:SITES", //delete
  VIEW_SITES: "VIEW:SITES", //view

  // designations
  READ_DESIGNATIONS: "READ:DESIGNATIONS", //get
  CREATE_DESIGNATIONS: "CREATE:DESIGNATIONS", //post
  EDIT_DESIGNATIONS: "EDIT:DESIGNATIONS", //put
  DELETE_DESIGNATIONS: "DELETE:DESIGNATIONS", //delete
  VIEW_DESIGNATIONS: "VIEW:DESIGNATIONS", //

  // zones
  READ_ZONES: "READ:ZONES",
  CREATE_ZONES: "CREATE:ZONES",
  EDIT_ZONES: "EDIT:ZONES",
  DELETE_ZONES: "DELETE:ZONES",
  VIEW_ZONES: "VIEW:ZONES",

  // Departments
  READ_DEPARTMENTS: "READ:DEPARTMENTS",
  CREATE_DEPARTMENTS: "CREATE:DEPARTMENTS",
  EDIT_DEPARTMENTS: "EDIT:DEPARTMENTS",
  DELETE_DEPARTMENTS: "DELETE:DEPARTMENTS",
  VIEW_DEPARTMENTS: "VIEW:DEPARTMENTS",

  // Notices
  READ_NOTICES: "READ:NOTICES",
  CREATE_NOTICES: "CREATE:NOTICES",
  EDIT_NOTICES: "EDIT:NOTICES",
  DELETE_NOTICES: "DELETE:NOTICES",
  VIEW_NOTICES: "VIEW:NOTICES",

  // Employees
  READ_EMPLOYEES: "READ:EMPLOYEES",
  CREATE_EMPLOYEES: "CREATE:EMPLOYEES",
  EDIT_EMPLOYEES: "EDIT:EMPLOYEES",
  DELETE_EMPLOYEES: "DELETE:EMPLOYEES",
  VIEW_EMPLOYEES: "VIEW:EMPLOYEES",

  // Employee Assignments
  READ_EMPLOYEE_ASSIGNMENTS: "READ:EMPLOYEE_ASSIGNMENTS",
  CREATE_EMPLOYEE_ASSIGNMENTS: "CREATE:EMPLOYEE_ASSIGNMENTS",
  DELETE_EMPLOYEE_ASSIGNMENTS: "DELETE:EMPLOYEE_ASSIGNMENTS",
  VIEW_EMPLOYEE_ASSIGNMENTS: "VIEW:EMPLOYEE_ASSIGNMENTS",

  // Categories
  READ_CATEGORIES: "READ:CATEGORIES",
  CREATE_CATEGORIES: "CREATE:CATEGORIES",
  EDIT_CATEGORIES: "EDIT:CATEGORIES",
  DELETE_CATEGORIES: "DELETE:CATEGORIES",
  VIEW_CATEGORIES: "VIEW:CATEGORIES",

  // SkillSets
  READ_SKILLSETS: "READ:SKILLSETS",
  CREATE_SKILLSETS: "CREATE:SKILLSETS",
  EDIT_SKILLSETS: "EDIT:SKILLSETS",
  DELETE_SKILLSETS: "DELETE:SKILLSETS",
  VIEW_SKILLSETS: "VIEW:SKILLSETS",

  // ManpowerSuppliers
  READ_MANPOWER_SUPPLIERS: "READ:MANPOWER_SUPPLIERS",
  CREATE_MANPOWER_SUPPLIERS: "CREATE:MANPOWER_SUPPLIERS",
  EDIT_MANPOWER_SUPPLIERS: "EDIT:MANPOWER_SUPPLIERS",
  DELETE_MANPOWER_SUPPLIERS: "DELETE:MANPOWER_SUPPLIERS",
  VIEW_MANPOWER_SUPPLIERS: "VIEW:MANPOWER_SUPPLIERS",

  // Manpowers
  READ_MANPOWER: "READ:MANPOWER",
  CREATE_MANPOWER: "CREATE:MANPOWER",
  EDIT_MANPOWER: "EDIT:MANPOWER",
  DELETE_MANPOWER: "DELETE:MANPOWER",
  VIEW_MANPOWER: "VIEW:MANPOWER",

  // MinimumWages
  READ_MIN_WAGES: "READ:MIN_WAGES",
  CREATE_MIN_WAGES: "CREATE:MIN_WAGES",
  EDIT_MIN_WAGES: "EDIT:MIN_WAGES",
  DELETE_MIN_WAGES: "DELETE:MIN_WAGES",
  VIEW_MIN_WAGES: "VIEW:MIN_WAGES",

  // AssignManpowers Test permission
  READ_MANPOWER_ASSIGNMENTS: "READ:MANPOWER_ASSIGNMENTS",
  CREATE_MANPOWER_ASSIGNMENTS: "CREATE:MANPOWER_ASSIGNMENTS",
  EDIT_MANPOWER_ASSIGNMENTS: "EDIT:MANPOWER_ASSIGNMENTS",
  DELETE_MANPOWER_ASSIGNMENTS: "DELETE:MANPOWER_ASSIGNMENTS",
  VIEW_MANPOWER_ASSIGNMENTS: "VIEW:MANPOWER_ASSIGNMENTS",

  // Manpower Transfer Test permissions
  READ_MANPOWER_TRANSFERS: "READ:MANPOWER_TRANSFERS",
  CREATE_MANPOWER_TRANSFERS: "CREATE:MANPOWER_TRANSFERS",
  EDIT_MANPOWER_TRANSFERS: "EDIT:MANPOWER_TRANSFERS",
  DELETE_MANPOWER_TRANSFERS: "DELETE:MANPOWER_TRANSFERS",
  APPROVE_MANPOWER_TRANSFERS: "APPROVE:MANPOWER_TRANSFERS",
  VIEW_MANPOWER_TRANSFERS: "VIEW:MANPOWER_TRANSFERS",

  // Attendance  Test permissions
  READ_ATTENDANCES: "READ:ATTENDANCES",
  CREATE_ATTENDANCES: "CREATE:ATTENDANCES",
  EDIT_ATTENDANCES: "EDIT:ATTENDANCES",
  DELETE_ATTENDANCES: "DELETE:ATTENDANCES",
  VIEW_ATTENDANCES: "VIEW:ATTENDANCES",

  // Payrolls Permissions
  READ_PAYSLIPS: "READ:PAYSLIPS",
  GENERATE_PAYSLIPS: "GENERATE:PAYSLIPS",

  // DailyConsumptions
  READ_DAILY_CONSUMPTIONS: "READ:DAILY_CONSUMPTIONS",
  CREATE_DAILY_CONSUMPTIONS: "CREATE:DAILY_CONSUMPTIONS",
  VIEW_DAILY_CONSUMPTIONS: "VIEW:DAILY_CONSUMPTIONS",

  READ_PURCHASE_ORDERS: "READ:PURCHASE_ORDERS",
  CREATE_PURCHASE_ORDERS: "CREATE:PURCHASE_ORDERS",
  EDIT_PURCHASE_ORDERS: "EDIT:PURCHASE_ORDERS",
  DELETE_PURCHASE_ORDERS: "DELETE:PURCHASE_ORDERS",
  APPROVE_PURCHASE_ORDERS_L1: "APPROVE:PURCHASE_ORDERS_L1",
  APPROVE_PURCHASE_ORDERS_L2: "APPROVE:PURCHASE_ORDERS_L2",
  COMPLETE_PURCHASE_ORDERS: "COMPLETE:PURCHASE_ORDERS",
  SUSPEND_PURCHASE_ORDERS: "SUSPEND:PURCHASE_ORDERS",
  UPDATE_PURCHASE_ORDER_REMARKS: "UPDATE:PURCHASE_ORDER_REMARKS",
  UPDATE_PURCHASE_ORDER_BILL_STATUS: "UPDATE:PURCHASE_ORDER_BILL_STATUS",

  // READ_WORK_ORDER_BILLS: "READ:WORK_ORDER_BILLS",
  // CREATE_WORK_ORDER_BILLS: "CREATE:WORK_ORDER_BILLS",
  // EDIT_WORK_ORDER_BILLS: "EDIT:WORK_ORDER_BILLS",
  // DELETE_WORK_ORDER_BILLS: "DELETE:WORK_ORDER_BILLS",

  READ_INWARD_DELIVERY_CHALLAN: "READ:INWARD_DELIVERY_CHALLAN",
  CREATE_INWARD_DELIVERY_CHALLAN: "CREATE:INWARD_DELIVERY_CHALLAN",
  EDIT_INWARD_DELIVERY_CHALLAN: "EDIT:INWARD_DELIVERY_CHALLAN",

  // Inward bills
  READ_INWARD_BILL: "READ:INWARD_BILL",
  CREATE_INWARD_BILL: "CREATE:INWARD_BILL",
  VIEW_INWARD_BILL: "VIEW:INWARD_BILL",
  EDIT_INWARD_BILL: "EDIT:INWARD_BILL",

  //inward bill paymet
  ADD_INWARD_BILL_PAYMENT: "ADD:INWARD_BILL_PAYMENT",
  DELETE_INWARD_BILL_PAYMENT: "DELETE:INWARD_BILL_PAYMENT",

  // Outward Delivery Challan permissions
  READ_OUTWARD_DELIVERY_CHALLAN: "READ:OUTWARD_DELIVERY_CHALLAN",
  VIEW_OUTWARD_DELIVERY_CHALLAN: "VIEW:OUTWARD_DELIVERY_CHALLAN",
  CREATE_OUTWARD_DELIVERY_CHALLAN: "CREATE:OUTWARD_DELIVERY_CHALLAN",
  APPROVE_OUTWARD_DELIVERY_CHALLAN: "APPROVE:OUTWARD_DELIVERY_CHALLAN",
  ACCEPT_OUTWARD_DELIVERY_CHALLAN: "ACCEPT:OUTWARD_DELIVERY_CHALLAN",

  // READ_WORK_ORDERS: "READ:WORK_ORDERS",
  // CREATE_WORK_ORDERS: "CREATE:WORK_ORDERS",
  // EDIT_WORK_ORDERS: "EDIT:WORK_ORDERS",
  // DELETE_WORK_ORDERS: "DELETE:WORK_ORDERS",
  // VIEW_WORK_ORDERS: "VIEW:WORK_ORDERS",

  // Unit permissions
  READ_UNITS: "READ:UNITS",
  CREATE_UNITS: "CREATE:UNITS",
  EDIT_UNITS: "EDIT:UNITS",
  DELETE_UNITS: "DELETE:UNITS",
  VIEW_UNITS: "VIEW:UNITS",
  // Asset Group permissions
  READ_ASSET_GROUPS: "READ:ASSET_GROUPS",
  CREATE_ASSET_GROUPS: "CREATE:ASSET_GROUPS",
  EDIT_ASSET_GROUPS: "EDIT:ASSET_GROUPS",
  DELETE_ASSET_GROUPS: "DELETE:ASSET_GROUPS",
  VIEW_ASSET_GROUPS: "VIEW:ASSET_GROUPS",
  // Asset Category permissions
  READ_ASSET_CATEGORIES: "READ:ASSET_CATEGORIES",
  CREATE_ASSET_CATEGORIES: "CREATE:ASSET_CATEGORIES",
  EDIT_ASSET_CATEGORIES: "EDIT:ASSET_CATEGORIES",
  DELETE_ASSET_CATEGORIES: "DELETE:ASSET_CATEGORIES",
  VIEW_ASSET_CATEGORIES: "VIEW:ASSET_CATEGORIES",

  // Item Category permissions
  READ_ITEM_CATEGORIES: "READ:ITEM_CATEGORIES",
  CREATE_ITEM_CATEGORIES: "CREATE:ITEM_CATEGORIES",
  EDIT_ITEM_CATEGORIES: "EDIT:ITEM_CATEGORIES",
  DELETE_ITEM_CATEGORIES: "DELETE:ITEM_CATEGORIES",
  // Items permissions
  READ_ITEMS: "READ:ITEMS",
  CREATE_ITEMS: "CREATE:ITEMS",
  EDIT_ITEMS: "EDIT:ITEMS",
  DELETE_ITEMS: "DELETE:ITEMS",
  VIEW_ITEMS: "VIEW:ITEMS",
  // Billing Address permissions
  READ_BILLING_ADDRESSES: "READ:BILLING_ADDRESSES",
  CREATE_BILLING_ADDRESSES: "CREATE:BILLING_ADDRESSES",
  EDIT_BILLING_ADDRESSES: "EDIT:BILLING_ADDRESSES",
  DELETE_BILLING_ADDRESSES: "DELETE:BILLING_ADDRESSES",
  // Vendor permissions
  READ_VENDORS: "READ:VENDORS",
  CREATE_VENDORS: "CREATE:VENDORS",
  EDIT_VENDORS: "EDIT:VENDORS",
  DELETE_VENDORS: "DELETE:VENDORS",
  VIEW_VENDORS: "VIEW:VENDORS",
  // BOQ permissions
  READ_BOQS: "READ:BOQS",
  CREATE_BOQS: "CREATE:BOQS",
  EDIT_BOQS: "EDIT:BOQS",
  DELETE_BOQS: "DELETE:BOQS",
  VIEW_BOQS: "VIEW:BOQS",

  // BOQ Bills permissions
  READ_BOQ_BILLS: "READ:BOQ_BILLS",
  CREATE_BOQ_BILLS: "CREATE:BOQ_BILLS",
  EDIT_BOQ_BILLS: "EDIT:BOQ_BILLS",
  DELETE_BOQ_BILLS: "DELETE:BOQ_BILLS",
  VIEW_BOQ_BILLS: "VIEW:BOQ_BILLS",
  // Daily Progress permissions
  READ_DAILY_PROGRESSES: "READ:DAILY_PROGRESSES",
  CREATE_DAILY_PROGRESSES: "CREATE:DAILY_PROGRESSES",
  EDIT_DAILY_PROGRESSES: "EDIT:DAILY_PROGRESSES",
  DELETE_DAILY_PROGRESSES: "DELETE:DAILY_PROGRESSES",
  VIEW_DAILY_PROGRESSES: "VIEW:DAILY_PROGRESSES",
  // Payment Terms permissions
  READ_PAYMENT_TERMS: "READ:PAYMENT_TERMS",
  CREATE_PAYMENT_TERMS: "CREATE:PAYMENT_TERMS",
  EDIT_PAYMENT_TERMS: "EDIT:PAYMENT_TERMS",
  DELETE_PAYMENT_TERMS: "DELETE:PAYMENT_TERMS",
  VIEW_PAYMENT_TERMS: "VIEW:PAYMENT_TERMS",

  // Cashbook Heads permissions
  READ_CASHBOOK_HEADS: "READ:CASHBOOK_HEADS",
  CREATE_CASHBOOK_HEADS: "CREATE:CASHBOOK_HEADS",
  EDIT_CASHBOOK_HEADS: "EDIT:CASHBOOK_HEADS",
  DELETE_CASHBOOK_HEADS: "DELETE:CASHBOOK_HEADS",
  VIEW_CASHBOOK_HEADS: "VIEW:CASHBOOK_HEADS",
  // Cashbook Budgets permissions
  READ_CASHBOOK_BUDGETS: "READ:CASHBOOK_BUDGETS",
  CREATE_CASHBOOK_BUDGETS: "CREATE:CASHBOOK_BUDGETS",
  EDIT_CASHBOOK_BUDGETS: "EDIT:CASHBOOK_BUDGETS",
  DELETE_CASHBOOK_BUDGETS: "DELETE:CASHBOOK_BUDGETS",
  VIEW_CASHBOOK_BUDGETS: "VIEW:CASHBOOK_BUDGETS",

  // Cashbook permissions
  READ_CASHBOOKS: "READ:CASHBOOKS",
  CREATE_CASHBOOKS: "CREATE:CASHBOOKS",
  EDIT_CASHBOOKS: "EDIT:CASHBOOKS",
  DELETE_CASHBOOKS: "DELETE:CASHBOOKS",
  VIEW_CASHBOOKS: "VIEW:CASHBOOKS",
  APPROVE_CASHBOOKS_L1: "APPROVE:CASHBOOKS_L1",
  APPROVE_CASHBOOKS_L2: "APPROVE:CASHBOOKS_L2",
  // Indent permissions
  READ_INDENTS: "READ:INDENTS",
  CREATE_INDENTS: "CREATE:INDENTS",
  EDIT_INDENTS: "EDIT:INDENTS",
  DELETE_INDENTS: "DELETE:INDENTS",
  VIEW_INDENTS: "VIEW:INDENTS",
  APPROVE_INDENTS_L1: "APPROVE:INDENTS_L1",
  APPROVE_INDENTS_L2: "APPROVE:INDENTS_L2",
  COMPLETE_INDENTS: "COMPLETE:INDENTS",
  SUSPEND_INDENTS: "SUSPEND:INDENTS",
  GENERATE_PO_FROM_INDENT: "GENERATE:PO_FROM_INDENT",

  // Site Budget permissions
  READ_SITE_BUDGETS: "READ:SITE_BUDGETS",
  CREATE_SITE_BUDGETS: "CREATE:SITE_BUDGETS",
  EDIT_SITE_BUDGETS: "EDIT:SITE_BUDGETS",
  DELETE_SITE_BUDGETS: "DELETE:SITE_BUDGETS",
  VIEW_SITE_BUDGETS: "VIEW:SITE_BUDGETS",

  // Rental Category permissions
  READ_RENTAL_CATEGORIES: "READ:RENTAL_CATEGORIES",
  CREATE_RENTAL_CATEGORIES: "CREATE:RENTAL_CATEGORIES",
  EDIT_RENTAL_CATEGORIES: "EDIT:RENTAL_CATEGORIES",
  DELETE_RENTAL_CATEGORIES: "DELETE:RENTAL_CATEGORIES",
  VIEW_RENTAL_CATEGORIES: "VIEW:RENTAL_CATEGORIES",
  // Rent Type permissions
  READ_RENT_TYPES: "READ:RENT_TYPES",
  CREATE_RENT_TYPES: "CREATE:RENT_TYPES",
  EDIT_RENT_TYPES: "EDIT:RENT_TYPES",
  DELETE_RENT_TYPES: "DELETE:RENT_TYPES",
  VIEW_RENT_TYPES: "VIEW:RENT_TYPES",
  // Rent permissions
  READ_RENTS: "READ:RENTS",
  CREATE_RENTS: "CREATE:RENTS",
  EDIT_RENTS: "EDIT:RENTS",
  DELETE_RENTS: "DELETE:RENTS",
  VIEW_RENTS: "VIEW:RENTS",
  // Asset permissions
  READ_ASSETS: "READ:ASSETS",
  CREATE_ASSETS: "CREATE:ASSETS",
  EDIT_ASSETS: "EDIT:ASSETS",
  DELETE_ASSETS: "DELETE:ASSETS",
  VIEW_ASSETS: "VIEW:ASSETS",
  // Asset Transfer Permissions
  READ_ASSET_TRANSFERS: "READ:ASSET_TRANSFERS",
  CREATE_ASSET_TRANSFERS: "CREATE:ASSET_TRANSFERS",
  EDIT_ASSET_TRANSFERS: "EDIT:ASSET_TRANSFERS",
  DELETE_ASSET_TRANSFERS: "DELETE:ASSET_TRANSFERS",
  APPROVE_ASSET_TRANSFERS: "APPROVE:ASSET_TRANSFERS",
  VIEW_ASSET_TRANSFERS: "VIEW:ASSET_TRANSFERS",

  // Attendance Report Permissions
  VIEW_ATTENDANCE_REPORTS: "VIEW:ATTENDANCE_REPORTS",

  // satrt
  VIEW_ROLES: "VIEW:ROLES",
  EDIT_ROLES_PERMISSIONS: "EDIT:ROLES_PERMISSIONS",
  // end
} as const;

 // Optional: manual grouping of permissions for UI sections. Some UI files import
 // PERMISSION_GROUPS directly. Provide a minimal, safe default here so those
 // imports work without changing existing call-sites. Consumers may override or
 // extend this later if they need custom ordering/grouping.
 export const PERMISSION_GROUPS_LEGACY: {
  key: string;
  label: string;
  permissions: string[];
}[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    permissions: [PERMISSIONS.VIEW_DASHBOARD],
  },
  {
    key: "users",
    label: "Users",
    permissions: [
      PERMISSIONS.VIEW_USERS,
      PERMISSIONS.READ_USERS,
      PERMISSIONS.CREATE_USERS,
      PERMISSIONS.EDIT_USERS,
      PERMISSIONS.DELETE_USERS,
    ],
  },
  {
    key: "states",
    label: "States",
    permissions: [
      PERMISSIONS.VIEW_STATES,
      PERMISSIONS.READ_STATES,
      PERMISSIONS.CREATE_STATES,
      PERMISSIONS.EDIT_STATES,
      PERMISSIONS.DELETE_STATES,
    ],
  },
  {
    key: "cities",
    label: "Cities",
    permissions: [
      PERMISSIONS.VIEW_CITIES,
      PERMISSIONS.READ_CITIES,
      PERMISSIONS.CREATE_CITIES,
      PERMISSIONS.EDIT_CITIES,
      PERMISSIONS.DELETE_CITIES,
    ],
  },
  {
    key: "companies",
    label: "Companies",
    permissions: [
      PERMISSIONS.VIEW_COMPANIES,
      PERMISSIONS.READ_COMPANIES,
      PERMISSIONS.CREATE_COMPANIES,
      PERMISSIONS.EDIT_COMPANIES,
      PERMISSIONS.DELETE_COMPANIES,
    ],
  },
  {
    key: "sites",
    label: "Sites",
    permissions: [
      PERMISSIONS.VIEW_SITES,
      PERMISSIONS.READ_SITES,
      PERMISSIONS.CREATE_SITES,
      PERMISSIONS.EDIT_SITES,
      PERMISSIONS.DELETE_SITES,
    ],
  },
  {
    key: "departments",
    label: "Departments",
    permissions: [
      PERMISSIONS.VIEW_DEPARTMENTS,
      PERMISSIONS.READ_DEPARTMENTS,
      PERMISSIONS.CREATE_DEPARTMENTS,
      PERMISSIONS.EDIT_DEPARTMENTS,
      PERMISSIONS.DELETE_DEPARTMENTS,
    ],
  },
  {
    key: "designations",
    label: "Designations",
    permissions: [
      PERMISSIONS.VIEW_DESIGNATIONS,
      PERMISSIONS.READ_DESIGNATIONS,
      PERMISSIONS.CREATE_DESIGNATIONS,
      PERMISSIONS.EDIT_DESIGNATIONS,
      PERMISSIONS.DELETE_DESIGNATIONS,
    ],
  },
  {
    key: "zones",
    label: "Zones",
    permissions: [
      PERMISSIONS.VIEW_ZONES,
      PERMISSIONS.READ_ZONES,
      PERMISSIONS.CREATE_ZONES,
      PERMISSIONS.EDIT_ZONES,
      PERMISSIONS.DELETE_ZONES,
    ],
  },
  {
    key: "employees",
    label: "Employees",
    permissions: [
      PERMISSIONS.VIEW_EMPLOYEES,
      PERMISSIONS.READ_EMPLOYEES,
      PERMISSIONS.CREATE_EMPLOYEES,
      PERMISSIONS.EDIT_EMPLOYEES,
      PERMISSIONS.DELETE_EMPLOYEES,
      PERMISSIONS.VIEW_EMPLOYEE_ASSIGNMENTS,
      PERMISSIONS.READ_EMPLOYEE_ASSIGNMENTS,
      PERMISSIONS.CREATE_EMPLOYEE_ASSIGNMENTS,
      PERMISSIONS.DELETE_EMPLOYEE_ASSIGNMENTS,
    ],
  },
  {
    key: "categories",
    label: "Categories",
    permissions: [
      PERMISSIONS.VIEW_CATEGORIES,
      PERMISSIONS.READ_CATEGORIES,
      PERMISSIONS.CREATE_CATEGORIES,
      PERMISSIONS.EDIT_CATEGORIES,
      PERMISSIONS.DELETE_CATEGORIES,
    ],
  },
  {
    key: "notices",
    label: "Notices",
    permissions: [
      PERMISSIONS.VIEW_NOTICES,
      PERMISSIONS.READ_NOTICES,
      PERMISSIONS.CREATE_NOTICES,
      PERMISSIONS.EDIT_NOTICES,
      PERMISSIONS.DELETE_NOTICES,
    ],
  },
  {
    key: "stocks",
    label: "Stocks",
    permissions: [PERMISSIONS.VIEW_STOCKS, PERMISSIONS.READ_STOCKS],
  },
  {
    key: "stock_adjustments",
    label: "Stock Adjustments",
    permissions: [
      PERMISSIONS.VIEW_STOCK_ADJUSTMENTS,
      PERMISSIONS.READ_STOCK_ADJUSTMENTS,
      PERMISSIONS.CREATE_STOCK_ADJUSTMENTS,
    ],
  },
  {
    key: "manpower",
    label: "Manpower",
    permissions: [
      PERMISSIONS.VIEW_MANPOWER,
      PERMISSIONS.READ_MANPOWER,
      PERMISSIONS.EDIT_MANPOWER,
      PERMISSIONS.DELETE_MANPOWER,
      PERMISSIONS.VIEW_MANPOWER_SUPPLIERS,
      PERMISSIONS.READ_MANPOWER_SUPPLIERS,
      PERMISSIONS.EDIT_MANPOWER_SUPPLIERS,
      PERMISSIONS.DELETE_MANPOWER_SUPPLIERS,
      PERMISSIONS.VIEW_MANPOWER_ASSIGNMENTS,
      PERMISSIONS.READ_MANPOWER_ASSIGNMENTS,
      PERMISSIONS.CREATE_MANPOWER_ASSIGNMENTS,
      PERMISSIONS.EDIT_MANPOWER_ASSIGNMENTS,
      PERMISSIONS.DELETE_MANPOWER_ASSIGNMENTS,
      PERMISSIONS.VIEW_MANPOWER_TRANSFERS,
      PERMISSIONS.READ_MANPOWER_TRANSFERS,
      PERMISSIONS.CREATE_MANPOWER_TRANSFERS,
      PERMISSIONS.EDIT_MANPOWER_TRANSFERS,
      PERMISSIONS.DELETE_MANPOWER_TRANSFERS,
      PERMISSIONS.APPROVE_MANPOWER_TRANSFERS,
    ],
  },
  {
    key: "attendance",
    label: "Attendance",
    permissions: [
      PERMISSIONS.VIEW_ATTENDANCES,
      PERMISSIONS.READ_ATTENDANCES,
      PERMISSIONS.CREATE_ATTENDANCES,
      PERMISSIONS.EDIT_ATTENDANCES,
      PERMISSIONS.DELETE_ATTENDANCES,
    ],
  },
  {
    key: "attendance_reports",
    label: "Attendance Reports",
    permissions: [PERMISSIONS.VIEW_ATTENDANCE_REPORTS],
  },
  {
    key: "units",
    label: "Units",
    permissions: [
      PERMISSIONS.READ_UNITS,
      PERMISSIONS.CREATE_UNITS,
      PERMISSIONS.EDIT_UNITS,
      PERMISSIONS.DELETE_UNITS,
      PERMISSIONS.VIEW_UNITS,
    ],
  },
  {
    key: "items",
    label: "Items",
    permissions: [
      PERMISSIONS.READ_ITEM_CATEGORIES,
      PERMISSIONS.CREATE_ITEM_CATEGORIES,
      PERMISSIONS.EDIT_ITEM_CATEGORIES,
      PERMISSIONS.DELETE_ITEM_CATEGORIES,
      PERMISSIONS.READ_ITEMS,
      PERMISSIONS.CREATE_ITEMS,
      PERMISSIONS.EDIT_ITEMS,
      PERMISSIONS.DELETE_ITEMS,
    ],
  },
  {
    key: "billing_addresses",
    label: "Billing Addresses",
    permissions: [
      PERMISSIONS.READ_BILLING_ADDRESSES,
      PERMISSIONS.CREATE_BILLING_ADDRESSES,
      PERMISSIONS.EDIT_BILLING_ADDRESSES,
      PERMISSIONS.DELETE_BILLING_ADDRESSES,
    ],
  },
  {
    key: "vendors",
    label: "Vendors",
    permissions: [
      PERMISSIONS.READ_VENDORS,
      PERMISSIONS.CREATE_VENDORS,
      PERMISSIONS.EDIT_VENDORS,
      PERMISSIONS.DELETE_VENDORS,
    ],
  },
  {
    key: "boqs",
    label: "BOQs",
    permissions: [
      PERMISSIONS.READ_BOQS,
      PERMISSIONS.CREATE_BOQS,
      PERMISSIONS.EDIT_BOQS,
      PERMISSIONS.DELETE_BOQS,
      PERMISSIONS.VIEW_BOQS,
    ],
  },
  {
    key: "boq_bills",
    label: "BOQ Bills",
    permissions: [
      PERMISSIONS.READ_BOQ_BILLS,
      PERMISSIONS.CREATE_BOQ_BILLS,
      PERMISSIONS.EDIT_BOQ_BILLS,
      PERMISSIONS.DELETE_BOQ_BILLS,
    ],
  },
  {
    key: "daily_consumptions",
    label: "Daily Consumptions",
    permissions: [
      PERMISSIONS.VIEW_DAILY_CONSUMPTIONS,
      PERMISSIONS.READ_DAILY_CONSUMPTIONS,
      PERMISSIONS.CREATE_DAILY_CONSUMPTIONS,
    ],
  },
  {
    key: "daily_progresses",
    label: "Daily Progress",
    permissions: [
      PERMISSIONS.READ_DAILY_PROGRESSES,
      PERMISSIONS.CREATE_DAILY_PROGRESSES,
      PERMISSIONS.EDIT_DAILY_PROGRESSES,
      PERMISSIONS.DELETE_DAILY_PROGRESSES,
      PERMISSIONS.VIEW_DAILY_PROGRESSES,
    ],
  },
  {
    key: "payment_terms",
    label: "Payment Terms",
    permissions: [
      PERMISSIONS.READ_PAYMENT_TERMS,
      PERMISSIONS.CREATE_PAYMENT_TERMS,
      PERMISSIONS.EDIT_PAYMENT_TERMS,
      PERMISSIONS.DELETE_PAYMENT_TERMS,
    ],
  },
  {
    key: "assets",
    label: "Assets",
    permissions: [
      PERMISSIONS.READ_ASSET_GROUPS,
      PERMISSIONS.CREATE_ASSET_GROUPS,
      PERMISSIONS.EDIT_ASSET_GROUPS,
      PERMISSIONS.DELETE_ASSET_GROUPS,
      PERMISSIONS.VIEW_ASSET_GROUPS,
      PERMISSIONS.READ_ASSETS,
      PERMISSIONS.CREATE_ASSETS,
      PERMISSIONS.EDIT_ASSETS,
      PERMISSIONS.DELETE_ASSETS,
      PERMISSIONS.VIEW_ASSETS,
      PERMISSIONS.READ_ASSET_TRANSFERS,
      PERMISSIONS.CREATE_ASSET_TRANSFERS,
      PERMISSIONS.EDIT_ASSET_TRANSFERS,
      PERMISSIONS.DELETE_ASSET_TRANSFERS,
      PERMISSIONS.APPROVE_ASSET_TRANSFERS,
      PERMISSIONS.VIEW_ASSET_TRANSFERS,
    ],
  },
  {
    key: "rents",
    label: "Rent",
    permissions: [
      PERMISSIONS.READ_RENTAL_CATEGORIES,
      PERMISSIONS.CREATE_RENTAL_CATEGORIES,
      PERMISSIONS.EDIT_RENTAL_CATEGORIES,
      PERMISSIONS.DELETE_RENTAL_CATEGORIES,
      PERMISSIONS.VIEW_RENTAL_CATEGORIES,
      PERMISSIONS.READ_RENT_TYPES,
      PERMISSIONS.CREATE_RENT_TYPES,
      PERMISSIONS.EDIT_RENT_TYPES,
      PERMISSIONS.DELETE_RENT_TYPES,
      PERMISSIONS.VIEW_RENT_TYPES,
      PERMISSIONS.READ_RENTS,
      PERMISSIONS.CREATE_RENTS,
      PERMISSIONS.EDIT_RENTS,
      PERMISSIONS.DELETE_RENTS,
      PERMISSIONS.VIEW_RENTS,
    ],
  },
  {
    key: "site_budgets",
    label: "Site Budgets",
    permissions: [
      PERMISSIONS.READ_SITE_BUDGETS,
      PERMISSIONS.CREATE_SITE_BUDGETS,
      PERMISSIONS.EDIT_SITE_BUDGETS,
      PERMISSIONS.DELETE_SITE_BUDGETS,
      PERMISSIONS.VIEW_SITE_BUDGETS,
    ],
  },
  {
    key: "cashbooks",
    label: "Cashbook",
    permissions: [
      PERMISSIONS.READ_CASHBOOK_HEADS,
      PERMISSIONS.CREATE_CASHBOOK_HEADS,
      PERMISSIONS.EDIT_CASHBOOK_HEADS,
      PERMISSIONS.DELETE_CASHBOOK_HEADS,
      PERMISSIONS.VIEW_CASHBOOK_HEADS,
      PERMISSIONS.READ_CASHBOOKS,
      PERMISSIONS.CREATE_CASHBOOKS,
      PERMISSIONS.EDIT_CASHBOOKS,
      PERMISSIONS.DELETE_CASHBOOKS,
      PERMISSIONS.VIEW_CASHBOOKS,
      PERMISSIONS.APPROVE_CASHBOOKS_L1,
      PERMISSIONS.APPROVE_CASHBOOKS_L2,
    ],
  },
  {
    key: "indents",
    label: "Indents",
    permissions: [
      PERMISSIONS.READ_INDENTS,
      PERMISSIONS.CREATE_INDENTS,
      PERMISSIONS.EDIT_INDENTS,
      PERMISSIONS.DELETE_INDENTS,
      PERMISSIONS.APPROVE_INDENTS_L1,
      PERMISSIONS.APPROVE_INDENTS_L2,
      PERMISSIONS.COMPLETE_INDENTS,
      PERMISSIONS.SUSPEND_INDENTS,
      PERMISSIONS.GENERATE_PO_FROM_INDENT,
    ],
  },
  {
    key: "payroll",
    label: "Payroll",
    permissions: [
      PERMISSIONS.READ_PAYSLIPS,
      PERMISSIONS.GENERATE_PAYSLIPS,
    ],
  },
  {
    key: "purchase_orders",
    label: "Purchase Orders",
    permissions: [
      PERMISSIONS.READ_PURCHASE_ORDERS,
      PERMISSIONS.CREATE_PURCHASE_ORDERS,
      PERMISSIONS.EDIT_PURCHASE_ORDERS,
      PERMISSIONS.DELETE_PURCHASE_ORDERS,
      PERMISSIONS.APPROVE_PURCHASE_ORDERS_L1,
      PERMISSIONS.APPROVE_PURCHASE_ORDERS_L2,
      PERMISSIONS.COMPLETE_PURCHASE_ORDERS,
      PERMISSIONS.SUSPEND_PURCHASE_ORDERS,
      PERMISSIONS.UPDATE_PURCHASE_ORDER_REMARKS,
      PERMISSIONS.UPDATE_PURCHASE_ORDER_BILL_STATUS,
    ],
  },
  // {
  //   key: "work_orders",
  //   label: "Work Orders",
  //   permissions: [
  //     PERMISSIONS.READ_WORK_ORDERS,
  //     PERMISSIONS.CREATE_WORK_ORDERS,
  //     PERMISSIONS.EDIT_WORK_ORDERS,
  //     PERMISSIONS.DELETE_WORK_ORDERS,
  //     PERMISSIONS.READ_WORK_ORDER_BILLS,
  //     PERMISSIONS.CREATE_WORK_ORDER_BILLS,
  //     PERMISSIONS.EDIT_WORK_ORDER_BILLS,
  //     PERMISSIONS.DELETE_WORK_ORDER_BILLS,
  //   ],
  // },
  {
    key: "delivery_challans",
    label: "Delivery Challans",
    permissions: [
      PERMISSIONS.READ_INWARD_DELIVERY_CHALLAN,
      PERMISSIONS.CREATE_INWARD_DELIVERY_CHALLAN,
      PERMISSIONS.EDIT_INWARD_DELIVERY_CHALLAN,
      PERMISSIONS.READ_OUTWARD_DELIVERY_CHALLAN,
      PERMISSIONS.CREATE_OUTWARD_DELIVERY_CHALLAN,
      PERMISSIONS.APPROVE_OUTWARD_DELIVERY_CHALLAN,
      PERMISSIONS.ACCEPT_OUTWARD_DELIVERY_CHALLAN,
    ],
  },
  {
    key: "inward_bills",
    label: "Inward Bills",
    permissions: [
      PERMISSIONS.READ_INWARD_BILL,
      PERMISSIONS.CREATE_INWARD_BILL,
      PERMISSIONS.VIEW_INWARD_BILL,
      PERMISSIONS.EDIT_INWARD_BILL,
      PERMISSIONS.ADD_INWARD_BILL_PAYMENT,
      PERMISSIONS.DELETE_INWARD_BILL_PAYMENT,
    ],
  },
  {
    key: "access_control",
    label: "Access Control",
    permissions: [
      PERMISSIONS.VIEW_ROLES,
      PERMISSIONS.EDIT_ROLES_PERMISSIONS,
    ],
  },
  // start
   {
    key: "cashbook_budgets",
    label: "Cashbook Budget",
    permissions: [PERMISSIONS.READ_CASHBOOK_BUDGETS,
                  PERMISSIONS.CREATE_CASHBOOK_BUDGETS,
                PERMISSIONS.EDIT_CASHBOOK_BUDGETS,
                PERMISSIONS.DELETE_CASHBOOK_BUDGETS,
              PERMISSIONS.VIEW_CASHBOOK_BUDGETS],
  },
   {
    key: "skillsets",
    label: "Skillset",
    permissions: [PERMISSIONS.READ_SKILLSETS,
                  PERMISSIONS.CREATE_SKILLSETS,
                  PERMISSIONS.EDIT_SKILLSETS,
                PERMISSIONS.DELETE_SKILLSETS,
                PERMISSIONS.VIEW_SKILLSETS,
              ],
  },
   {
    key: "min_wages",
    label: "Min Wages",
    permissions: [PERMISSIONS.READ_MIN_WAGES,
                  PERMISSIONS.CREATE_MIN_WAGES,
                  PERMISSIONS.EDIT_MIN_WAGES,
                PERMISSIONS.DELETE_MIN_WAGES,
                PERMISSIONS.VIEW_MIN_WAGES,
              ],
  },
   {
    key: "asset_categories",
    label: "Assets Categories",
    permissions: [PERMISSIONS.READ_ASSET_CATEGORIES,
                  PERMISSIONS.EDIT_ASSET_CATEGORIES,
                PERMISSIONS.DELETE_ASSET_CATEGORIES,
                PERMISSIONS.VIEW_ASSET_CATEGORIES,
                                PERMISSIONS.CREATE_ASSET_CATEGORIES,

              ],
  },
];

export const PERMISSION_GROUPS = PERMISSION_GROUPS_LEGACY;

export const ROLES = {
  ADMIN: "Admin",
  SITE_ADMIN: "Site Admin",
  COMMERCIAL_HEAD: "Commercial Head",
  MANAGING_DIRECTOR: "Managing Director",
  SITE_INCHARGE: "Site Incharge",
  OFFICE_ASSISTANT: "Office Assistant",
  TECHNICAL_SUPPORT: "Technical Support",
  TRAINEE_ENGINEER: "Trainee Engineer",
  ACCOUNT_EXECUTIVE: "Account Executive",
  JUNIOR_ACCOUNTANT: "Junior Accountant",
  SENIOR_HR_EXECUTIVE: "Senior HR Executive",
  SITE_SUPERVISOR: "Site Supervisor",
  PROJECT_DIRECTOR: "Project Director",
  HR_ASSISTANT: "HR Assistant",

  ASSISTANT_ENGINEER: "Assistant Engineer",
  TENDER_EXECUTIVE: "Tender Executive",
  SENIOR_PROJECT_MANAGER: "Senior Project Manager",
  JUNIOR_ENGINEER: "Junior Engineer",
  WORK_ASSISTANT: "Work Assistant",
  SAFETY_SUPERVISOR: "Safety Supervisor",
  SENIOR_SITE_SUPERVISOR: "Senior Site Supervisor",
  PROJECT_ENGINEER: "Project Engineer",

  ASSISTANT_MANAGER_PROJECTS: "Assistant Manager - Projects",
  SENIOR_ACCOUNTANT: "Senior Accountant",
  ASSISTANT_MANAGER: "Assistant Manager",
  DIRECTOR: "Director",
  SENIOR_PROJECT_ENGINEER: "Senior Project Engineer",
  MECHANIC: "Mechanic",
  PROJECT_COORDINATOR: "Project Coordinator",
  PURCHASE_EXECUTIVE: "Purchase Executive",
  ELECTRICIAN: "Electrician",
  SCAFFOLDING_INSPECTOR: "Scaffolding Inspector",
  ESTIMATION_ENGINEER: "Estimation Engineer",
  ACCOUNT_ASSISTANT: "Account Assistant",
  PROJECT_MANAGER: "Project Manager",
  ASSISTANT_MANAGER_EHS: "Assistant Manager - EHS",
  GENERAL_MANAGER_FINANCE_ADMIN_COMM: "General Manager (Finance, Admin, Comm)",
  DIVING_SUPERVISOR: "Diving Supervisor",
  TECHNICAL_DIRECTOR: "Technical Director",
} as const;
