// RBAC constants: stable permission & role identifiers plus role->permission mapping.
// Extend by adding new PERMISSIONS keys and including them in relevant ROLES_PERMISSIONS entries.
export const PERMISSIONS = {
  // Core / Dashboard
  VIEW_DASHBOARD: "VIEW:DASHBOARD",

  // Users (existing internal management)
  READ_USERS: "READ:USERS",
  EDIT_USERS: "EDIT:USERS",
  DELETE_USERS: "MANAGE:USERS",

  // Projects
  CREATE_PROJECT: "CREATE:PROJECT", // create new project (Admin only)
  READ_PROJECT: "READ:PROJECT", // view project(s)
  EDIT_PROJECT: "EDIT:PROJECT", // edit project metadata
  DELETE_PROJECT: "DELETE:PROJECT", // delete project
  MANAGE_PROJECT_USERS: "MANAGE:PROJECT:USERS", // add/remove users to project

  // Project Files
  UPLOAD_PROJECT_FILE: "UPLOAD:PROJECT:FILE", // upload / attach file to project
  READ_PROJECT_FILE: "READ:PROJECT:FILE", // download/view project files
  DELETE_PROJECT_FILE: "DELETE:PROJECT:FILE", // remove project files
  // Blocks & Cracks
  IMPORT_CRACKS: "IMPORT:CRACKS", // import crack identifications via Excel
  READ_CRACKS: "READ:CRACKS",
  MANAGE_BLOCKS: "MANAGE:BLOCKS",
  // Design Maps
  READ_DESIGN_MAP: "READ:DESIGN:MAP",
  WRITE_DESIGN_MAP: "WRITE:DESIGN:MAP",
  // Cities
  READ_CITIES: "READ:CITIES",
  EDIT_CITIES: "EDIT:CITIES",
  DELETE_CITIES: "DELETE:CITIES",
  // State permissions
  READ_STATES: "READ:STATES",
  EDIT_STATES: "EDIT:STATES",
  DELETE_STATES: "DELETE:STATES",
  // Company permissions
  READ_COMPANIES: "READ:COMPANIES",
  EDIT_COMPANIES: "EDIT:COMPANIES",
  DELETE_COMPANIES: "DELETE:COMPANIES",
  // Site permissions
  READ_SITES: "READ:SITES",
  EDIT_SITES: "EDIT:SITES",
  DELETE_SITES: "DELETE:SITES",
  // Department permissions
  READ_DEPARTMENTS: "READ:DEPARTMENTS",
  EDIT_DEPARTMENTS: "EDIT:DEPARTMENTS",
  DELETE_DEPARTMENTS: "DELETE:DEPARTMENTS",
  // Employee permissions
  READ_EMPLOYEES: "READ:EMPLOYEES",
  EDIT_EMPLOYEES: "EDIT:EMPLOYEES",
  DELETE_EMPLOYEES: "DELETE:EMPLOYEES",
  // Manpower Supplier permissions
  READ_MANPOWER_SUPPLIERS: "READ:MANPOWER:SUPPLIERS",
  EDIT_MANPOWER_SUPPLIERS: "EDIT:MANPOWER:SUPPLIERS",
  DELETE_MANPOWER_SUPPLIERS: "DELETE:MANPOWER:SUPPLIERS",
  // Manpower (workers) permissions
  READ_MANPOWER: "READ:MANPOWER",
  EDIT_MANPOWER: "EDIT:MANPOWER",
  DELETE_MANPOWER: "DELETE:MANPOWER",
  // Category permissions
  READ_CATEGORIES: "READ:CATEGORIES",
  EDIT_CATEGORIES: "EDIT:CATEGORIES",
  DELETE_CATEGORIES: "DELETE:CATEGORIES",
  // Skill Set permissions
  READ_SKILLSETS: "READ:SKILLSETS",
  EDIT_SKILLSETS: "EDIT:SKILLSETS",
  DELETE_SKILLSETS: "DELETE:SKILLSETS",
  // Minimum Wages permissions
  READ_MIN_WAGES: "READ:MIN_WAGES",
  EDIT_MIN_WAGES: "EDIT:MIN_WAGES",
  DELETE_MIN_WAGES: "DELETE:MIN_WAGES",
  // Unit permissions
  READ_UNITS: "READ:UNITS",
  EDIT_UNITS: "EDIT:UNITS",
  DELETE_UNITS: "DELETE:UNITS",
  // Asset Group permissions
  READ_ASSET_GROUPS: "READ:ASSET_GROUPS",
  EDIT_ASSET_GROUPS: "EDIT:ASSET_GROUPS",
  DELETE_ASSET_GROUPS: "DELETE:ASSET_GROUPS",
  // Asset Category permissions
  READ_ASSET_CATEGORIES: "READ:ASSET_CATEGORIES",
  EDIT_ASSET_CATEGORIES: "EDIT:ASSET_CATEGORIES",
  DELETE_ASSET_CATEGORIES: "DELETE:ASSET_CATEGORIES",
  // Item Category permissions
  READ_ITEM_CATEGORIES: "READ:ITEM:CATEGORIES",
  CREATE_ITEM_CATEGORIES: "CREATE:ITEM:CATEGORIES",
  EDIT_ITEM_CATEGORIES: "EDIT:ITEM:CATEGORIES",
  DELETE_ITEM_CATEGORIES: "DELETE:ITEM:CATEGORIES",
  // Items permissions
  READ_ITEMS: "READ:ITEMS",
  CREATE_ITEMS: "CREATE:ITEMS",
  EDIT_ITEMS: "EDIT:ITEMS",
  DELETE_ITEMS: "DELETE:ITEMS",
  // Billing Address permissions
  READ_BILLING_ADDRESSES: "READ:BILLING:ADDRESSES",
  CREATE_BILLING_ADDRESSES: "CREATE:BILLING:ADDRESSES",
  EDIT_BILLING_ADDRESSES: "EDIT:BILLING:ADDRESSES",
  DELETE_BILLING_ADDRESSES: "DELETE:BILLING:ADDRESSES",
  // Vendor permissions
  READ_VENDORS: "READ:VENDORS",
  CREATE_VENDORS: "CREATE:VENDORS",
  EDIT_VENDORS: "EDIT:VENDORS",
  DELETE_VENDORS: "DELETE:VENDORS",
  // BOQ permissions
  READ_BOQS: "READ:BOQS",
  EDIT_BOQS: "EDIT:BOQS",
  DELETE_BOQS: "DELETE:BOQS",
  // Daily Progress permissions
  READ_DAILY_PROGRESSES: "READ:DAILY_PROGRESSES",
  EDIT_DAILY_PROGRESSES: "EDIT:DAILY_PROGRESSES",
  DELETE_DAILY_PROGRESSES: "DELETE:DAILY_PROGRESSES",
  // Payment Terms permissions
  READ_PAYMENT_TERMS: "READ:PAYMENT:TERMS",
  CREATE_PAYMENT_TERMS: "CREATE:PAYMENT:TERMS",
  EDIT_PAYMENT_TERMS: "EDIT:PAYMENT:TERMS",
  DELETE_PAYMENT_TERMS: "DELETE:PAYMENT:TERMS",

  // Cashbook Heads permissions
  READ_CASHBOOK_HEADS: "READ:CASHBOOK:HEADS",
  EDIT_CASHBOOK_HEADS: "EDIT:CASHBOOK:HEADS",
  DELETE_CASHBOOK_HEADS: "DELETE:CASHBOOK:HEADS",
  // Cashbook Budgets permissions
  READ_CASHBOOK_BUDGETS: "READ:CASHBOOK:BUDGETS",
  CREATE_CASHBOOK_BUDGETS: "CREATE:CASHBOOK:BUDGETS",
  EDIT_CASHBOOK_BUDGETS: "EDIT:CASHBOOK:BUDGETS",
  DELETE_CASHBOOK_BUDGETS: "DELETE:CASHBOOK:BUDGETS",
  // Cashbook permissions
  READ_CASHBOOKS: "READ:CASHBOOKS",
  CREATE_CASHBOOKS: "CREATE:CASHBOOKS",
  EDIT_CASHBOOKS: "EDIT:CASHBOOKS",
  DELETE_CASHBOOKS: "DELETE:CASHBOOKS",
  // Indent permissions
  READ_INDENTS: "READ:INDENTS",
  CREATE_INDENTS: "CREATE:INDENTS",
  EDIT_INDENTS: "EDIT:INDENTS",
  DELETE_INDENTS: "DELETE:INDENTS",

  // Site Budget permissions
  READ_SITE_BUDGETS: "READ:SITE:BUDGETS",
  CREATE_SITE_BUDGETS: "CREATE:SITE:BUDGETS",
  EDIT_SITE_BUDGETS: "EDIT:SITE:BUDGETS",
  DELETE_SITE_BUDGETS: "DELETE:SITE:BUDGETS",

  // Rental Category permissions
  READ_RENTAL_CATEGORIES: "READ:RENTAL:CATEGORIES",
  EDIT_RENTAL_CATEGORIES: "EDIT:RENTAL:CATEGORIES",
  DELETE_RENTAL_CATEGORIES: "DELETE:RENTAL:CATEGORIES",
  // Rent Type permissions
  READ_RENT_TYPES: "READ:RENT:TYPES",
  EDIT_RENT_TYPES: "EDIT:RENT:TYPES",
  DELETE_RENT_TYPES: "DELETE:RENT:TYPES",
  // Rent permissions
  READ_RENTS: "READ:RENTS",
  CREATE_RENTS: "CREATE:RENTS",
  EDIT_RENTS: "EDIT:RENTS",
  DELETE_RENTS: "DELETE:RENTS",
  // Asset permissions
  READ_ASSETS: "READ:ASSETS",
  CREATE_ASSETS: "CREATE:ASSETS",
  EDIT_ASSETS: "EDIT:ASSETS",
  DELETE_ASSETS: "DELETE:ASSETS",
  // Asset Transfer Permissions
  READ_ASSET_TRANSFERS: "READ:ASSET:TRANSFERS",
  CREATE_ASSET_TRANSFERS: "CREATE:ASSET:TRANSFERS",
  EDIT_ASSET_TRANSFERS: "EDIT:ASSET:TRANSFERS",
  DELETE_ASSET_TRANSFERS: "DELETE:ASSET:TRANSFERS",
  APPROVE_ASSET_TRANSFERS: "APPROVE:ASSET:TRANSFERS",

  // Manpower Assignment permissions
  READ_MANPOWER_ASSIGNMENTS: "READ:MANPOWER:ASSIGNMENTS",
  CREATE_MANPOWER_ASSIGNMENTS: "CREATE:MANPOWER:ASSIGNMENTS",
  EDIT_MANPOWER_ASSIGNMENTS: "EDIT:MANPOWER:ASSIGNMENTS",
  DELETE_MANPOWER_ASSIGNMENTS: "DELETE:MANPOWER:ASSIGNMENTS",
  // Manpower Transfer permissions
  READ_MANPOWER_TRANSFERS: "READ:MANPOWER:TRANSFERS",
  CREATE_MANPOWER_TRANSFERS: "CREATE:MANPOWER:TRANSFERS",
  EDIT_MANPOWER_TRANSFERS: "EDIT:MANPOWER:TRANSFERS",
  DELETE_MANPOWER_TRANSFERS: "DELETE:MANPOWER:TRANSFERS",
  APPROVE_MANPOWER_TRANSFERS: "APPROVE:MANPOWER:TRANSFERS",

  // Notice Permissions
  READ_NOTICES: "READ:NOTICES",
  CREATE_NOTICES: "CREATE:NOTICES",
  EDIT_NOTICES: "EDIT:NOTICES",
  DELETE_NOTICES: "DELETE:NOTICES",

  // Attendance Permissions
  READ_ATTENDANCES: "READ:ATTENDANCES",
  CREATE_ATTENDANCES: "CREATE:ATTENDANCES",
  EDIT_ATTENDANCES: "EDIT:ATTENDANCES",
  DELETE_ATTENDANCES: "DELETE:ATTENDANCES",

  // Attendance Report Permissions
  VIEW_ATTENDANCE_REPORTS: "VIEW:ATTENDANCE:REPORTS",
} as const;

export const ROLES = {
  ADMIN: "admin", // full system access
  USER: "user", // internal staff (can see dashboard, read projects/users, but not create projects or upload files)
  PROJECT_MANAGER: "pm", // project manager
  HR: "HR", // HR
  SITE_ENGINEER: "siteEng", // site engineer

  PROJECT_USER: "project_user", // external / client user tied to specific projects (can only read its own project + files)
} as const;

export const ROLES_PERMISSIONS = {
  // Admin: everything
  [ROLES.ADMIN]: [...Object.values(PERMISSIONS)],

  // Internal staff user: can view dashboard, read users & projects & project files (but no creation/upload/delete)
  [ROLES.USER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.READ_USERS,
    PERMISSIONS.READ_PROJECT,
    PERMISSIONS.READ_PROJECT_FILE,
    PERMISSIONS.READ_CRACKS,
    PERMISSIONS.READ_DESIGN_MAP,
    PERMISSIONS.READ_CITIES,
    PERMISSIONS.READ_STATES,
    PERMISSIONS.READ_COMPANIES,
    PERMISSIONS.READ_SITES,
    PERMISSIONS.READ_DEPARTMENTS,
    PERMISSIONS.READ_EMPLOYEES,
    PERMISSIONS.READ_MANPOWER_SUPPLIERS,
    PERMISSIONS.READ_MANPOWER,
    PERMISSIONS.READ_CATEGORIES,
    PERMISSIONS.READ_SKILLSETS,
    PERMISSIONS.READ_MIN_WAGES,
    PERMISSIONS.READ_UNITS,
    PERMISSIONS.READ_ASSET_GROUPS,
    PERMISSIONS.READ_ASSET_CATEGORIES,
    PERMISSIONS.READ_ITEM_CATEGORIES,
    PERMISSIONS.READ_ITEMS,
    PERMISSIONS.READ_BILLING_ADDRESSES,
    PERMISSIONS.READ_VENDORS,
    PERMISSIONS.READ_BOQS,
    PERMISSIONS.READ_PAYMENT_TERMS,
    PERMISSIONS.READ_CASHBOOK_HEADS,
    PERMISSIONS.READ_CASHBOOK_BUDGETS,
    PERMISSIONS.READ_CASHBOOKS,
    PERMISSIONS.READ_INDENTS,
    PERMISSIONS.READ_SITE_BUDGETS,
    PERMISSIONS.READ_RENTAL_CATEGORIES,
    PERMISSIONS.READ_RENT_TYPES,
    PERMISSIONS.READ_RENTS,
    PERMISSIONS.READ_ASSETS,
    PERMISSIONS.READ_ASSET_TRANSFERS,
    PERMISSIONS.READ_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.READ_MANPOWER_TRANSFERS,
    PERMISSIONS.READ_NOTICES,
    PERMISSIONS.READ_ATTENDANCES,
    // keep create/edit attendances for internal staff (from yash)
    PERMISSIONS.CREATE_ATTENDANCES,
    PERMISSIONS.EDIT_ATTENDANCES,
    PERMISSIONS.VIEW_ATTENDANCE_REPORTS,
  ],

  // Project (client) user: minimal – only read project + its files (no dashboard access if you prefer; remove if needed)
  [ROLES.PROJECT_USER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.READ_PROJECT,
    PERMISSIONS.READ_PROJECT_FILE,
    PERMISSIONS.READ_CRACKS,
    PERMISSIONS.READ_DESIGN_MAP,
    PERMISSIONS.READ_CITIES,
    PERMISSIONS.READ_STATES,
    PERMISSIONS.READ_COMPANIES,
    PERMISSIONS.READ_SITES,
    PERMISSIONS.READ_DEPARTMENTS,
    PERMISSIONS.READ_EMPLOYEES,
    PERMISSIONS.READ_MANPOWER_SUPPLIERS,
    PERMISSIONS.READ_MANPOWER,
    PERMISSIONS.READ_CATEGORIES,
    PERMISSIONS.READ_SKILLSETS,
    PERMISSIONS.READ_MIN_WAGES,
    PERMISSIONS.READ_UNITS,
    PERMISSIONS.READ_ASSET_GROUPS,
    PERMISSIONS.READ_ASSET_CATEGORIES,
    PERMISSIONS.READ_ITEM_CATEGORIES,
    PERMISSIONS.READ_ITEMS,
    PERMISSIONS.READ_BILLING_ADDRESSES,
    PERMISSIONS.READ_VENDORS,
    PERMISSIONS.READ_BOQS,
    PERMISSIONS.READ_PAYMENT_TERMS,
    PERMISSIONS.READ_CASHBOOK_HEADS,
    PERMISSIONS.READ_CASHBOOK_BUDGETS,
    PERMISSIONS.READ_CASHBOOKS,
    PERMISSIONS.READ_INDENTS,
    PERMISSIONS.READ_SITE_BUDGETS,
    PERMISSIONS.READ_RENTAL_CATEGORIES,
    PERMISSIONS.READ_RENT_TYPES,
    PERMISSIONS.READ_RENTS,
    PERMISSIONS.READ_ASSETS,
    PERMISSIONS.READ_ASSET_TRANSFERS,
    PERMISSIONS.READ_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.READ_MANPOWER_TRANSFERS,
    PERMISSIONS.READ_NOTICES,
    PERMISSIONS.READ_ATTENDANCES,
    // keep create_attendances on project_user as in yash (remove if clients shouldn't create attendance)
    PERMISSIONS.CREATE_ATTENDANCES,
    PERMISSIONS.VIEW_ATTENDANCE_REPORTS,
  ],

  [ROLES.PROJECT_MANAGER]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,

    // MANPOWER
    PERMISSIONS.READ_MANPOWER,
    PERMISSIONS.EDIT_MANPOWER,
    PERMISSIONS.DELETE_MANPOWER,

    // MANPOWER_ASSIGNMENTS
    PERMISSIONS.READ_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.CREATE_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.EDIT_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.DELETE_MANPOWER_ASSIGNMENTS,

    // ATTENDANCES
    PERMISSIONS.READ_ATTENDANCES,
    PERMISSIONS.CREATE_ATTENDANCES,
    PERMISSIONS.VIEW_ATTENDANCE_REPORTS,

    // RENTS
    PERMISSIONS.READ_RENTS,
    PERMISSIONS.CREATE_RENTS,
    PERMISSIONS.EDIT_RENTS,
    PERMISSIONS.DELETE_RENTS,

    // Cashbook Heads
    PERMISSIONS.READ_CASHBOOK_HEADS,
    PERMISSIONS.EDIT_CASHBOOK_HEADS,
    PERMISSIONS.DELETE_CASHBOOK_HEADS,

    // Cashbook Budgets
    PERMISSIONS.READ_CASHBOOK_BUDGETS,
    PERMISSIONS.CREATE_CASHBOOK_BUDGETS,
    PERMISSIONS.EDIT_CASHBOOK_BUDGETS,
    PERMISSIONS.DELETE_CASHBOOK_BUDGETS,

    // Cashbook
    PERMISSIONS.READ_CASHBOOKS,
    PERMISSIONS.CREATE_CASHBOOKS,
    PERMISSIONS.EDIT_CASHBOOKS,
    PERMISSIONS.DELETE_CASHBOOKS,

    // ITEM
    PERMISSIONS.READ_ITEMS,
    PERMISSIONS.CREATE_ITEMS,
    PERMISSIONS.EDIT_ITEMS,
    PERMISSIONS.DELETE_ITEMS,

    // INDENTS
    PERMISSIONS.READ_INDENTS,
    PERMISSIONS.CREATE_INDENTS,
    PERMISSIONS.EDIT_INDENTS,
    PERMISSIONS.DELETE_INDENTS,

    // ASSETS
    PERMISSIONS.READ_ASSETS,
    PERMISSIONS.CREATE_ASSETS,
    PERMISSIONS.EDIT_ASSETS,
    PERMISSIONS.DELETE_ASSETS,

    // ASSET_CATEGORIES
    PERMISSIONS.READ_ASSET_CATEGORIES,
    PERMISSIONS.EDIT_ASSET_CATEGORIES,
    PERMISSIONS.DELETE_ASSET_CATEGORIES,

    // ASSET_TRANSFERS
    PERMISSIONS.READ_ASSET_TRANSFERS,
    PERMISSIONS.CREATE_ASSET_TRANSFERS,
    PERMISSIONS.EDIT_ASSET_TRANSFERS,
    PERMISSIONS.DELETE_ASSET_TRANSFERS,
    PERMISSIONS.APPROVE_ASSET_TRANSFERS,

    // ASSET_GROUPS
    PERMISSIONS.READ_ASSET_GROUPS,
    PERMISSIONS.EDIT_ASSET_GROUPS,
    PERMISSIONS.DELETE_ASSET_GROUPS,

    // BOQS
    PERMISSIONS.READ_BOQS,
    PERMISSIONS.EDIT_BOQS,
    PERMISSIONS.DELETE_BOQS,
  ],

  [ROLES.SITE_ENGINEER]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,

    // MANPOWER
    PERMISSIONS.READ_MANPOWER,
    PERMISSIONS.EDIT_MANPOWER,
    PERMISSIONS.DELETE_MANPOWER,

    // ATTENDANCES
    PERMISSIONS.READ_ATTENDANCES,
    PERMISSIONS.CREATE_ATTENDANCES,
    PERMISSIONS.VIEW_ATTENDANCE_REPORTS,

    // Cashbook Heads
    PERMISSIONS.READ_CASHBOOK_HEADS,
    PERMISSIONS.EDIT_CASHBOOK_HEADS,
    PERMISSIONS.DELETE_CASHBOOK_HEADS,

    // Cashbook Budgets
    PERMISSIONS.READ_CASHBOOK_BUDGETS,
    PERMISSIONS.CREATE_CASHBOOK_BUDGETS,
    PERMISSIONS.EDIT_CASHBOOK_BUDGETS,
    PERMISSIONS.DELETE_CASHBOOK_BUDGETS,

    // Cashbook
    PERMISSIONS.READ_CASHBOOKS,
    PERMISSIONS.CREATE_CASHBOOKS,
    PERMISSIONS.EDIT_CASHBOOKS,
    PERMISSIONS.DELETE_CASHBOOKS,

    // ITEM
    PERMISSIONS.READ_ITEMS,
    PERMISSIONS.CREATE_ITEMS,
    PERMISSIONS.EDIT_ITEMS,
    PERMISSIONS.DELETE_ITEMS,

    // INDENTS
    PERMISSIONS.READ_INDENTS,
    PERMISSIONS.CREATE_INDENTS,
    PERMISSIONS.EDIT_INDENTS,
    PERMISSIONS.DELETE_INDENTS,

    // ASSETS
    PERMISSIONS.READ_ASSETS,
    PERMISSIONS.CREATE_ASSETS,
    PERMISSIONS.EDIT_ASSETS,
    PERMISSIONS.DELETE_ASSETS,

    // ASSET_TRANSFERS
    PERMISSIONS.READ_ASSET_TRANSFERS,
    PERMISSIONS.CREATE_ASSET_TRANSFERS,
    PERMISSIONS.EDIT_ASSET_TRANSFERS,
    PERMISSIONS.DELETE_ASSET_TRANSFERS,
    PERMISSIONS.APPROVE_ASSET_TRANSFERS,

    // BOQS
    PERMISSIONS.READ_BOQS,
    PERMISSIONS.EDIT_BOQS,
    PERMISSIONS.DELETE_BOQS,
  ],

  [ROLES.HR]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,

    // State
    PERMISSIONS.READ_STATES,
    PERMISSIONS.EDIT_STATES,
    PERMISSIONS.DELETE_STATES,

    // Cities
    PERMISSIONS.READ_CITIES,
    PERMISSIONS.EDIT_CITIES,
    PERMISSIONS.DELETE_CITIES,

    // Site
    PERMISSIONS.READ_SITES,
    PERMISSIONS.EDIT_SITES,
    PERMISSIONS.DELETE_SITES,

    // Department
    PERMISSIONS.READ_DEPARTMENTS,
    PERMISSIONS.EDIT_DEPARTMENTS,
    PERMISSIONS.DELETE_DEPARTMENTS,

    // EMPLOYEES
    PERMISSIONS.READ_EMPLOYEES,
    PERMISSIONS.EDIT_EMPLOYEES,
    PERMISSIONS.DELETE_EMPLOYEES,

    // NOTICES
    PERMISSIONS.READ_NOTICES,
    PERMISSIONS.CREATE_NOTICES,
    PERMISSIONS.EDIT_NOTICES,
    PERMISSIONS.DELETE_NOTICES,

    // CATEGORIES
    PERMISSIONS.READ_CATEGORIES,
    PERMISSIONS.EDIT_CATEGORIES,
    PERMISSIONS.DELETE_CATEGORIES,

    // SKILLSETS
    PERMISSIONS.READ_SKILLSETS,
    PERMISSIONS.EDIT_SKILLSETS,
    PERMISSIONS.DELETE_SKILLSETS,

    // MANPOWER_SUPPLIERS
    PERMISSIONS.READ_MANPOWER_SUPPLIERS,
    PERMISSIONS.EDIT_MANPOWER_SUPPLIERS,
    PERMISSIONS.DELETE_MANPOWER_SUPPLIERS,

    // READ_MANPOWER
    PERMISSIONS.READ_MANPOWER,
    PERMISSIONS.EDIT_MANPOWER,
    PERMISSIONS.DELETE_MANPOWER,

    // MIN_WAGES
    PERMISSIONS.READ_MIN_WAGES,
    PERMISSIONS.EDIT_MIN_WAGES,
    PERMISSIONS.DELETE_MIN_WAGES,

    // MANPOWER_ASSIGNMENTS
    PERMISSIONS.READ_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.CREATE_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.EDIT_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.DELETE_MANPOWER_ASSIGNMENTS,

    // ATTENDANCES
    PERMISSIONS.READ_ATTENDANCES,
    PERMISSIONS.CREATE_ATTENDANCES,
    PERMISSIONS.VIEW_ATTENDANCE_REPORTS,

    // Cashbook Heads
    PERMISSIONS.READ_CASHBOOK_HEADS,
    PERMISSIONS.EDIT_CASHBOOK_HEADS,
    PERMISSIONS.DELETE_CASHBOOK_HEADS,

    // Cashbook Budgets
    PERMISSIONS.READ_CASHBOOK_BUDGETS,
    PERMISSIONS.CREATE_CASHBOOK_BUDGETS,
    PERMISSIONS.EDIT_CASHBOOK_BUDGETS,
    PERMISSIONS.DELETE_CASHBOOK_BUDGETS,

    // Cashbook
    PERMISSIONS.READ_CASHBOOKS,
    PERMISSIONS.CREATE_CASHBOOKS,
    PERMISSIONS.EDIT_CASHBOOKS,
    PERMISSIONS.DELETE_CASHBOOKS,

    // ITEM
    PERMISSIONS.READ_ITEMS,
    PERMISSIONS.CREATE_ITEMS,
    PERMISSIONS.EDIT_ITEMS,
    PERMISSIONS.DELETE_ITEMS,

    // INDENTS
    PERMISSIONS.READ_INDENTS,
    PERMISSIONS.CREATE_INDENTS,
    PERMISSIONS.EDIT_INDENTS,
    PERMISSIONS.DELETE_INDENTS,

    // ASSETS
    PERMISSIONS.READ_ASSETS,
    PERMISSIONS.CREATE_ASSETS,
    PERMISSIONS.EDIT_ASSETS,
    PERMISSIONS.DELETE_ASSETS,

    // ASSET_TRANSFERS
    PERMISSIONS.READ_ASSET_TRANSFERS,
    PERMISSIONS.CREATE_ASSET_TRANSFERS,
    PERMISSIONS.EDIT_ASSET_TRANSFERS,
    PERMISSIONS.DELETE_ASSET_TRANSFERS,
    PERMISSIONS.APPROVE_ASSET_TRANSFERS,

    // ASSET_CATEGORIES
    PERMISSIONS.READ_ASSET_CATEGORIES,
    PERMISSIONS.EDIT_ASSET_CATEGORIES,
    PERMISSIONS.DELETE_ASSET_CATEGORIES,
  ],
} as const;
